Config:
    #API endpoint URL, required
    api-url: {apiURL}
    #API token string, required
    token: {token}
    #submission ID, required
    submission: {submissionID}
    #upload type,  valid value in [data file, metadata], required
    type: data file
    #folder that contains either data files (type = file) or metadata (TSV/TXT) files (type = metadata), required
    data: {dataFolder}
    #path to manifest file, conditional required when type = file
    manifest: {manifest}
    #file name header name in the manifest file, default is file_name
    name-field: {name-field}
    #file id header name in the manifest file in data model
    id-field: {id-field}
    # if id_field need to be DCF prefix id, read from data model content.json
    omit-DCF-prefix: {omit-DCF-prefix}
    #file size header name in the manifest file, default is file_size
    size-field: {size-field}
    #file md5 header name in the manifest file, default is md5sum
    md5-field: {md5-field}
    #file uploading retries
    retries: 3
    # if overwrite existed file
    overwrite: false
    # if only run file validation without uploading
    dryrun: false